function [w, i, T] = simulate(R, L, K, Jm)
    w_ = evalin('caller','length(data)');
    f = w_.f;
    DATA_SAMPLING_FREQUENCY = w_.DATA_SAMPLING_FREQUENCY;
    SIMULATION_DURATION = w_.SIMULATION_DURATION;
    STEP_OPT = w_.STEP_OPT;
    
    sys_w = tf(K, [ ...
       L*Jm, ...
       R*Jm + f*L, ... 
       K*K + f*R ...
       ]);
   
    sys_i = tf([Jm f], [ ...
       L*Jm, ...
       R*Jm + f*L, ... 
       K*K + f*R ...
       ]);
   
    [w] = step(sys_w, 0:1/DATA_SAMPLING_FREQUENCY:SIMULATION_DURATION, STEP_OPT);
    [i, T] = step(sys_i, 0:1/w_.DATA_SAMPLING_FREQUENCY:SIMULATION_DURATION, STEP_OPT);
end

